# Generated by Django 6.0.5 on 2026-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, verbose_name='uuid')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
    ]
